disabled_rules:
- trailing_whitespace
- force_cast
opt_in_rules:
- empty_count
- empty_string
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
line_length:
    warning: 200
    error: 220
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 200
    error: 300
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 400
    error: 600
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 20
    error: 30
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  allowed_symbols: ["_"]
  excluded: ["id", "i", "j", "k", "S0", "q", "x", "y"]

reporter: "xcode"
